In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/raw/premier_league")

files = sorted(DATA_DIR.glob("E0_*.csv"))

print(f"Liczba plików: {len(files)}")

for file in files:
    print(file.name)

Liczba plików: 22
E0_0405.csv
E0_0506.csv
E0_0607.csv
E0_0708.csv
E0_0809.csv
E0_0910.csv
E0_1011.csv
E0_1112.csv
E0_1213.csv
E0_1314.csv
E0_1415.csv
E0_1516.csv
E0_1617.csv
E0_1718.csv
E0_1819.csv
E0_1920.csv
E0_2021.csv
E0_2122.csv
E0_2223.csv
E0_2324.csv
E0_2425.csv
E0_2526.csv

In [15]:
dfs = []

for file in files:
    if file.name == "E0_0405.csv":
        df = pd.read_csv(
            file,
            encoding="cp1252",
            engine="python",
            usecols=range(57)
        )
    else:
        df = pd.read_csv(
            file,
            encoding="cp1252"
        )

    df["Season"] = file.stem.replace("E0_", "")
    dfs.append(df)

data = pd.concat(dfs, ignore_index=True)

print(f"Liczba meczów: {len(data)}")
print(f"Liczba kolumn: {len(data.columns)}")

Liczba meczów: 8361
Liczba kolumn: 203

C:\Users\Acer\AppData\Local\Temp\ipykernel_17836\2804233236.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Season"] = file.stem.replace("E0_", "")

In [16]:
print(data.shape)
print(data.columns.tolist())

(8361, 203)
['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'GBH', 'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'SBH', 'SBD', 'SBA', 'WHH', 'WHD', 'WHA', 'GB>2.5', 'GB<2.5', 'B365>2.5', 'B365<2.5', 'GBAHH', 'GBAHA', 'GBAH', 'LBAHH', 'LBAHA', 'LBAH', 'B365AHH', 'B365AHA', 'B365AH', 'Season', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'BSH', 'BSD', 'BSA', 'PSH', 'PSD', 'PSA', 'PSCH', 'PSCD', 'PSCA', 'Time', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'ï»¿Div', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA', 'BFDH', 'BFDD', 'BFDA', 'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'CLH', 'CLD', 'CLA', 'BFDCH', 'BFDCD', 'BFDCA', 'BMGMCH', 'BMGMCD', 'BMGMCA', 'BVCH', 'BVCD', 'BVCA', 'CLCH', 'CLCD', 'CLCA', 'LBCH', 'LBCD', 'LBCA']

In [17]:
data.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,14/08/04,Aston Villa,Southampton,2.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/04,Blackburn,West Brom,1.0,1.0,D,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/04,Bolton,Charlton,4.0,1.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/04,Man City,Fulham,1.0,1.0,D,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/04,Middlesbrough,Newcastle,2.0,2.0,D,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8361 entries, 0 to 8360
Columns: 203 entries, Div to LBCA
dtypes: float64(193), str(10)
memory usage: 12.9 MB

In [19]:
data[["Season", "Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR"]].head(10)

  Season      Date       HomeTeam        AwayTeam  FTHG  FTAG FTR
0   0405  14/08/04    Aston Villa     Southampton   2.0   0.0   H
1   0405  14/08/04      Blackburn       West Brom   1.0   1.0   D
2   0405  14/08/04         Bolton        Charlton   4.0   1.0   H
3   0405  14/08/04       Man City          Fulham   1.0   1.0   D
4   0405  14/08/04  Middlesbrough       Newcastle   2.0   2.0   D
5   0405  14/08/04        Norwich  Crystal Palace   1.0   1.0   D
6   0405  14/08/04     Portsmouth      Birmingham   1.0   1.0   D
7   0405  14/08/04      Tottenham       Liverpool   1.0   1.0   D
8   0405  15/08/04        Chelsea      Man United   1.0   0.0   H
9   0405  15/08/04        Everton         Arsenal   1.0   4.0   A

In [20]:
print(data["Season"].value_counts().sort_index())

Season
0405    380
0506    380
0607    380
0708    380
0809    380
0910    380
1011    380
1112    380
1213    380
1314    380
1415    381
1516    380
1617    380
1718    380
1819    380
1920    380
2021    380
2122    380
2223    380
2324    380
2425    380
2526    380
Name: count, dtype: int64

In [21]:
print(data["FTR"].value_counts())

FTR
H    3809
A    2500
D    2051
Name: count, dtype: int64

In [22]:
missing = data.isna().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

CLCA       8101
CLCH       8101
CLCD       8101
LBCH       8080
LBCA       8080
           ...
AST           1
HST           1
AS            1
HS            1
Referee       1
Length: 202, dtype: int64

In [23]:
print(f"Liczba wszystkich brakujących wartości: {data.isna().sum().sum()}")

Liczba wszystkich brakujących wartości: 1014138

In [24]:
print(f"Liczba duplikatów: {data.duplicated().sum()}")

Liczba duplikatów: 0

In [25]:
important_cols = [
    "Date",
    "HomeTeam",
    "AwayTeam",
    "FTHG",
    "FTAG",
    "FTR"
]

print(data[important_cols].isna().sum())

Date        1
HomeTeam    1
AwayTeam    1
FTHG        1
FTAG        1
FTR         1
dtype: int64

In [26]:
print(data[important_cols].dtypes)

Date            str
HomeTeam        str
AwayTeam        str
FTHG        float64
FTAG        float64
FTR             str
dtype: object

In [27]:
print(data[important_cols].isna().any(axis=1).sum())

1

In [28]:
data[data[important_cols].isna().any(axis=1)]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
4180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
data[data["Season"] == "1415"].tail()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
4176,E0,24/05/15,Leicester,QPR,5.0,1.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4177,E0,24/05/15,Man City,Southampton,2.0,0.0,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4178,E0,24/05/15,Newcastle,West Ham,2.0,0.0,H,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4179,E0,24/05/15,Stoke,Liverpool,6.0,1.0,H,5.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
data = data.dropna(subset=important_cols).copy()

print(f"Liczba meczów po usunięciu pustych rekordów: {len(data)}")

Liczba meczów po usunięciu pustych rekordów: 8360

In [33]:
data["Date"] = pd.to_datetime(
    data["Date"],
    format="%d/%m/%y"
)

In [34]:
print(data["Date"].min())
print(data["Date"].max())

2004-08-14 00:00:00
2026-05-24 00:00:00

In [35]:
data = data.sort_values("Date").reset_index(drop=True)

In [36]:
print(data[["Date", "HomeTeam", "AwayTeam"]].head())
print(data[["Date", "HomeTeam", "AwayTeam"]].tail())

        Date       HomeTeam     AwayTeam
0 2004-08-14    Aston Villa  Southampton
1 2004-08-14      Blackburn    West Brom
2 2004-08-14         Bolton     Charlton
3 2004-08-14       Man City       Fulham
4 2004-08-14  Middlesbrough    Newcastle
           Date        HomeTeam    AwayTeam
8355 2026-05-24  Crystal Palace     Arsenal
8356 2026-05-24         Burnley      Wolves
8357 2026-05-24        Brighton  Man United
8358 2026-05-24          Fulham   Newcastle
8359 2026-05-24        West Ham       Leeds

In [37]:
development_data = data[data["Season"] != "2526"].copy()
final_test_data = data[data["Season"] == "2526"].copy()

print("Development:", len(development_data))
print("Final test:", len(final_test_data))

Development: 7980
Final test: 380

In [38]:
from pathlib import Path

output_path = Path("../data/processed")
output_path.mkdir(parents=True, exist_ok=True)

data.to_csv(
    output_path / "matches.csv",
    index=False
)

print("Zapisano:", output_path / "matches.csv")
print("Liczba rekordów:", len(data))

Zapisano: ..\data\processed\matches.csv
Liczba rekordów: 8360

In [39]:
test = pd.read_csv("../data/processed/matches.csv")

print(test.shape)
print(test.head())

(8360, 203)
  Div        Date       HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
0  E0  2004-08-14    Aston Villa  Southampton   2.0   0.0   H   2.0   0.0   H
1  E0  2004-08-14      Blackburn    West Brom   1.0   1.0   D   0.0   1.0   A
2  E0  2004-08-14         Bolton     Charlton   4.0   1.0   H   2.0   0.0   H
3  E0  2004-08-14       Man City       Fulham   1.0   1.0   D   1.0   0.0   H
4  E0  2004-08-14  Middlesbrough    Newcastle   2.0   2.0   D   0.0   1.0   A

   ... BMGMCA  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  LBCD  LBCA
0  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 203 columns]

C:\Users\Acer\AppData\Local\Temp\ipykernel_17836\2802114103.py:1: DtypeWarning: Columns (0: Div, 1: Time, 2: ï»¿Div) have mixed types. Specify dtype option on import or set low_memory=False.
  test = pd.read_csv("../data/processed/matches.csv")

In [40]:
# Usunięcie błędnej kolumny powstałej przez BOM
if "ï»¿Div" in data.columns:
    data = data.drop(columns=["ï»¿Div"])

# Usunięcie kolumny Time - nie będzie nam potrzebna w pierwszej wersji modelu
if "Time" in data.columns:
    data = data.drop(columns=["Time"])

print("Liczba kolumn:", len(data.columns))
print(data.columns.tolist())

Liczba kolumn: 201
['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'GBH', 'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'SBH', 'SBD', 'SBA', 'WHH', 'WHD', 'WHA', 'GB>2.5', 'GB<2.5', 'B365>2.5', 'B365<2.5', 'GBAHH', 'GBAHA', 'GBAH', 'LBAHH', 'LBAHA', 'LBAH', 'B365AHH', 'B365AHA', 'B365AH', 'Season', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'BSH', 'BSD', 'BSA', 'PSH', 'PSD', 'PSA', 'PSCH', 'PSCD', 'PSCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA', 'BFDH', 'BFDD', 'BFDA', 'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'CLH', 'CLD', 'CLA', 'BFDCH', 'BFDCD', 'BFDCA', 'BMGMCH', 'BMGMCD', 'BMGMCA', 'BVCH', 'BVCD', 'BVCA', 'CLCH', 'CLCD', 'CLCA', 'LBCH', 'LBCD', 'LBCA']

In [41]:
data.to_csv(
    "../data/processed/matches.csv",
    index=False
)

print("Zapisano poprawioną wersję matches.csv")

Zapisano poprawioną wersję matches.csv